/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietHoaDonDAO;
import DAO.HoaDonBanDAO;
import DAO.NhanVienDAO;
import POJO.ChiTietHoaDon;
import POJO.HoaDonBan;
import POJO.NhanVIen;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    DefaultTableModel tableModel = new DefaultTableModel();
    DefaultTableModel tableModel2 = new DefaultTableModel();
    public ThongKe() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] columnNames = { "Mã Hóa Đơn","Mã Nhân Viên","Thành Tiền","Ngày"};
        tbl_thongke.setModel(tableModel);
        tableModel.setColumnIdentifiers(columnNames);
        String[] columnNames2 = { "Mã Hóa Đơn","Mã Món Ăn","Số lượng","Giá","Thành TIền"};
        tbl_chitiet.setModel(tableModel2);
        tableModel2.setColumnIdentifiers(columnNames2);
        Print();
    }
    public void Print()
    {
        Object[] rows;
        try {
            HoaDonBanDAO pbd = new HoaDonBanDAO();
            ArrayList<HoaDonBan> pb = new ArrayList<HoaDonBan>();
            pb = pbd.layHDB();
            for (HoaDonBan hdb : pb) {
                rows = new Object[]{hdb.getMahd(), hdb.getManv(), hdb.getThanhtien(), hdb.getNgay()};
                tableModel.addRow(rows);
            }
            label_tt.setText(String.valueOf(pbd.TONGTIEN()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongke = new javax.swing.JTable();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        btn_tim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_tt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_chitiet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongkeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongke);

        jDateChooser.setDateFormatString("dd-MM-yyyy");

        btn_tim.setBackground(new java.awt.Color(255, 51, 0));
        btn_tim.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_tim.setText("TÌM");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tổng Tiền :");

        label_tt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_tt.setForeground(new java.awt.Color(255, 0, 0));

        tbl_chitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_chitiet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(label_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tim, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_tt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        tableModel.setRowCount(0);
        Date vd =  jDateChooser.getDate();
        DateFormat formatdate = new SimpleDateFormat("dd-MM-yyyy");
        Object[] rows;
        try {
            HoaDonBanDAO pbd = new HoaDonBanDAO();
            ArrayList<HoaDonBan> pb = new ArrayList<HoaDonBan>();
            pb = pbd.layHDBtheoNGAY(String.valueOf(formatdate.format(vd)));
            for (HoaDonBan hdb : pb) {
                rows = new Object[]{hdb.getMahd(), hdb.getManv(), hdb.getThanhtien(), hdb.getNgay()};
                tableModel.addRow(rows);
            }
            label_tt.setText(String.valueOf(pbd.TinhTongTienTheoNgay(String.valueOf(formatdate.format(vd)))));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_timActionPerformed

    public int MAHOADON;
    private void tbl_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongkeMouseClicked
        tableModel2.setRowCount(0);
        int row = this.tbl_thongke.getSelectedRow();
        int ma = (int)tbl_thongke.getValueAt(row, 0);
        MAHOADON = ma;
        System.out.println(MAHOADON);
        Object[] rows;
        try {
            ChiTietHoaDonDAO pbd = new ChiTietHoaDonDAO();
            ArrayList<ChiTietHoaDon> pb = new ArrayList<ChiTietHoaDon>();
            pb = pbd.layCTHDtheoHD(MAHOADON);
            
            for (ChiTietHoaDon hdb : pb) {
                String tenmon = pbd.layTENMONAN(hdb.getMamon());
                rows = new Object[]{hdb.getMahd(), tenmon, hdb.getSl(), hdb.getGia(),hdb.getThanhtien()};
                tableModel2.addRow(rows);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbl_thongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tim;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_tt;
    private javax.swing.JTable tbl_chitiet;
    private javax.swing.JTable tbl_thongke;
    // End of variables declaration//GEN-END:variables
}
