SET DATEFORMAT dmy;
CREATE DATABASE QL_NHAHANG
GO



CREATE TABLE NGUOIDUNG
(
	TENDANGNHAP VARCHAR(50) PRIMARY KEY NOT NULL,
	MATKHAU VARCHAR(50)
)

INSERT INTO NGUOIDUNG VALUES('admin','123abc'),('nhanvien','nhanvien')
SELECT * FROM NGUOIDUNG
CREATE TABLE LOAIMONAN
(
	MALOAIMON int IDENTITY(1,1) PRIMARY KEY,
	TENLOAIMON nvarchar(50)
)

CREATE TABLE NHACUNGCAP
(
	IDNCC int IDENTITY(1,1) PRIMARY KEY,
	TENNCC nvarchar(50),
	DIACHI nvarchar(100)
)
CREATE TABLE NGUYENLIEU
(
	MANGUYENLIEU int IDENTITY(1,1) PRIMARY KEY,
	TENGNUYENLIEU nvarchar(100),
	DONGIANHAP int,
	IDNCC int,
	SOLUONG int,
	CONSTRAINT fk_NL_NCC FOREIGN KEY (IDNCC) REFERENCES NHACUNGCAP(IDNCC)
)

CREATE TABLE PHIEUNHAP
(
	IDPHIEU int IDENTITY(1,1) PRIMARY KEY,
	IDNCC int,
	MANGUYENLIEU int,
	SOLUONG int,
	NGAYNHAO DATE,
	CONSTRAINT fk_PN_NCC FOREIGN KEY (IDNCC) REFERENCES NHACUNGCAP(IDNCC),
	CONSTRAINT fk_PN_NL FOREIGN KEY (MANGUYENLIEU) REFERENCES NGUYENLIEU(MANGUYENLIEU)
)
SELECT * FROM PHIEUNHAP
CREATE TABLE MONAN
(
	MAMON int IDENTITY(1,1) PRIMARY KEY,
	TENMON nvarchar(50),
	DONGIA int,
	MALOAIMON int,
	MANGUYENLIEU int,
	CONSTRAINT fk_LOAIMON FOREIGN KEY (MALOAIMON) REFERENCES LOAIMONAN(MALOAIMON),
	CONSTRAINT fk_MONAN_NGUYENLIEU FOREIGN KEY (MANGUYENLIEU) REFERENCES NGUYENLIEU(MANGUYENLIEU)
)

CREATE TABLE KHACHHANG
(
	MAKH int IDENTITY(1,1) PRIMARY KEY,
	HOTENKH nvarchar(50),
	DIENTHOAIKH nvarchar(20)
)


CREATE TABLE BAN
(
	MABAN int IDENTITY(1,1) PRIMARY KEY,
	SOGHE int,
	GHICHU nvarchar(100),
)


CREATE TABLE NHANVIEN
(
	MANV int IDENTITY(1,1) PRIMARY KEY,
	HOTENNV nvarchar(50),
	DIENTHOAINV nvarchar(20),
	NGAYSINH nvarchar(20),
)

INSERT INTO NHANVIEN VALUES(N'Tán Minh Trí','0306568225','03-08-2000'),
(N'Vương Quỳnh Hương','0837258388','22-02-2002');
CREATE TABLE HOADONBAN
(
	MAHD int IDENTITY(1,1) PRIMARY KEY,
	MANV int,
	THANHTIEN int,
	MABAN int,
	NGAY nvarchar(20),
	CONSTRAINT fk_HOADONBAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT fk_HOADONBAN_BAN FOREIGN KEY (MABAN) REFERENCES BAN(MABAN),
)
INSERT INTO HOADONBAN VALUES(1,0,1,'25-11-2023')
CREATE TABLE CHITIETHOADON
(
	MAHD int,
	MAMON int,
	SL int,
	DONGIA int,
	THANHTIEN int,
	CONSTRAINT pk_CTHD PRIMARY KEY (MAHD,MAMON),
	CONSTRAINT fk_CTHD_MONAN FOREIGN KEY (MAMON) REFERENCES MONAN(MAMON),
	CONSTRAINT fk_HOADONBAN_MONAN FOREIGN KEY (MAHD) REFERENCES HOADONBAN(MAHD)
)
INSERT INTO HOADONBAN VALUES(1,0,2,'25-11-2023')
SELECT * FROM BAN
	
SELECT * FROM CHITIETHOADON
SELECT * FROM LOAIMONAN
SELECT * FROM NGUYENLIEU
SELECT * FROM MONAN
SELECT * FROM NGUOIDUNG

SELECT * FROM NHANVIEN

INSERT INTO CHITIETHOADON VALUES(10,5,35000,SL*DONGIA)
UPDATE NGUYENLIEU SET SOLUONG = SOLUONG - 20 WHERE MANGUYENLIEU = 1
INSERT INTO BAN VALUES(4,NULL),
(4,NULL),
(4,NULL),
(4,NULL),
(4,NULL),
(4,NULL)


INSERT INTO LOAIMONAN
VALUES(N'Bánh Mì'),
(N'Mì'),
(N'Khoai Tây Chiên'),
(N'Gà Rán'),
(N'Kem'),
(N'Nước Ngọt');


INSERT INTO NGUYENLIEU
VALUES(N'Bột Bánh Mì',20000,1,200),
(N'Thịt bò',350000,1,200),
(N'Mì Ý',50000,1,200),
(N'Phô Mai',90000,1,200),
(N'Đùi Gà',130000,1,200),
(N'Cánh Gà',100000,1,200),
(N'Cà Rốt',135000,1,200),
(N'Cà Chua',100000,1,200),
(N'Ớt',60000,1,200),
(N'Thịt Heo',230000,1,200)

INSERT INTO NHACUNGCAP
VALUES(N'Công ty Thực Phẩm Thành Nam Food','TPHCM'),
(N'Công ty TNHH Thực phẩm Hữu Nghị','TPHCM')


INSERT INTO MONAN
VALUES(N'Bánh mì xúc xích',15000,1,1),
(N'Bò Nhúng Giấm',15000,1,2),
(N'Mỳ Ý Sốt ',15000,1,3),
(N'Mỳ Ý Phô Mai',15000,1,4),
(N'Đùi Gà chiên nước mắm',15000,1,5),
(N'Cánh gà chiên',15000,1,6),
(N'Thịt Kho trứng cút',15000,1,7)


SELECT SOLUONG FROM NGUYENLIEU WHERE MANGUYENLIEU = 1
SET DATEFORMAT dmy;
GO
CREATE TRIGGER trg_UpdateSoLuongNhap
ON PHIEUNHAP
AFTER INSERT
AS
BEGIN
    UPDATE NGUYENLIEU
    SET SOLUONG = NGUYENLIEU.SOLUONG + i.SOLUONG
    FROM NGUYENLIEU
    INNER JOIN inserted i ON NGUYENLIEU.MANGUYENLIEU = i.MANGUYENLIEU
END
SELECT * FROM NGUYENLIEU